name: CI/CD Pipeline - Medplus App

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      run: |
        aws configure set aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set aws-region: ${{ secrets.AWS_REGION }}

    - name: Log in to Amazon ECR
      run:
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 938882467274.dkr.ecr.us-east-1.amazonaws.com
      

    - name: Build and Push Docker Image to ECR
      run: |
        docker build -t favour${{ github.run_number }} .
        docker tag favour:${{ github.run_number }} 938882467274.dkr.ecr.us-east-1.amazonaws.com/favour:${{ github.run_number }}
        docker push 938882467274.dkr.ecr.us-east-1.amazonaws.com/favour:${{ github.run_number }}


  